---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  #fig.path = "https://raw.githubusercontent.com/jannes-m/RQGIS/master/figures/",
  fig.align = "center",
  collapse = TRUE,
  eval = FALSE,
  comment = "#>",
  cache = TRUE
)
```

### Run RStudio, RQGIS and QGIS in a Docker container

```{sh, eval=FALSE}
# clone the repository
git clone https://github.com/jannes-m/docker-rqgis.git
# navigate to the cloned directory
cd docker-rqgis
# build the docker image, and name it rqgis
sudo docker build -t rqgis .  
# start the container from the shell
docker run -it rqgis /bin/bash
# set the virtual display 
Xvfb :99 -ac -noreset &
# start R
R
```

Now you can run R commands, e.g.:

```{r, eval=FALSE}
library("RQGIS")
#> Loading required package: reticulate
qgis_session_info()
#> Assuming that your root path is '/usr'!
#> $qgis_version
#> [1] "2.18.25"
#> 
#> $gdal
#> [1] "2.1.2"
#> 
#> $grass6
#> [1] FALSE
#> 
#> $grass7
#> [1] "7.2.0"
#> 
#> $saga
#> NULL
```
