library("reticulate")
Sys.setenv(PYTHONPATH="/usr/share/qgis/python")
Sys.setenv(LD_LIBRARY_PATH="/usr/lib")
use_python("/usr/bin/python3", required = TRUE)
py_run_string("from pyvirtualdisplay import Display")
py_run_string("display = Display(visible=False, size=(1024, 768), color_depth=24)")
py_run_string("display.start()")

py_run_string("from qgis.core import *")
py_run_string("QgsApplication.setPrefixPath('/usr/bin/qgis', True)")
py_run_string("qgs = QgsApplication([], True)")
py_run_string("qgs.initQgis()")
